settings:
  title: 'zapEHR Status'
  url: 'https://status.zapehr.com' # used for Slack messages
  logo: _zapehr-logo-white.svg # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: zapehr-com
    name: zapehr.com
    url: 'https://zapehr.com'
    method: GET
    expectStatus: 200
  - id: docs-zapehr-com
    name: Documentation
    url: 'https://docs.zapehr.com'
    method: GET
    expectStatus: 200
  - id: console-zapehr-com
    name: Console
    url: 'https://console.zapehr.com'
    method: GET
    expectStatus: 200
  - id: fhir-api-zapehr-com
    name: FHIR API
    url: 'https://fhir-api.zapehr.com/version'
    method: GET
    expectStatus: 200
  - id: platform-api-zapehr-com
    name: Platform API
    url: 'https://platform-api.zapehr.com/v1/version'
    method: GET
    expectStatus: 200
  - id: project-api-zapehr-com
    name: Project API
    url: 'https://project-api.zapehr.com/v1/version'
    method: GET
    expectStatus: 200
